<?php
/**
 * DestinyRewardSourceCategory
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny\Definitions;
use \Bungie\D1\ObjectSerializer;

/**
 * DestinyRewardSourceCategory Class Doc Comment
 *
 * @category Class
 * @description BNet&#39;s custom categorization of reward sources. We took a look at the existing ways that items could be spawned, and tried to make high-level categorizations of them. This needs to be re-evaluated for Destiny 2.
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DestinyRewardSourceCategory
{
    /**
     * Possible values of this enum
     */
    const DESTINY_REWARD_SOURCE_CATEGORY_NONE = 0;
    const DESTINY_REWARD_SOURCE_CATEGORY_ACTIVITY = 1;
    const DESTINY_REWARD_SOURCE_CATEGORY_VENDOR = 2;
    const DESTINY_REWARD_SOURCE_CATEGORY_AGGREGATE = 3;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DESTINY_REWARD_SOURCE_CATEGORY_NONE,
            self::DESTINY_REWARD_SOURCE_CATEGORY_ACTIVITY,
            self::DESTINY_REWARD_SOURCE_CATEGORY_VENDOR,
            self::DESTINY_REWARD_SOURCE_CATEGORY_AGGREGATE,
        ];
    }
}


