<?php
/**
 * DestinyTalentNodeStepImpactEffects
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny\Definitions;
use \Bungie\D1\ObjectSerializer;

/**
 * DestinyTalentNodeStepImpactEffects Class Doc Comment
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DestinyTalentNodeStepImpactEffects
{
    /**
     * Possible values of this enum
     */
    const DESTINY_TALENT_NODE_STEP_IMPACT_EFFECTS_NONE = 0;
    const DESTINY_TALENT_NODE_STEP_IMPACT_EFFECTS_ARMORPIERCING = 1;
    const DESTINY_TALENT_NODE_STEP_IMPACT_EFFECTS_RICOCHET = 2;
    const DESTINY_TALENT_NODE_STEP_IMPACT_EFFECTS_FLINCH = 4;
    const DESTINY_TALENT_NODE_STEP_IMPACT_EFFECTS_COLLATERALDAMAGE = 8;
    const DESTINY_TALENT_NODE_STEP_IMPACT_EFFECTS_DISORIENT = 16;
    const DESTINY_TALENT_NODE_STEP_IMPACT_EFFECTS_HIGHLIGHTTARGET = 32;
    const DESTINY_TALENT_NODE_STEP_IMPACT_EFFECTS_ALL = 63;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DESTINY_TALENT_NODE_STEP_IMPACT_EFFECTS_NONE,
            self::DESTINY_TALENT_NODE_STEP_IMPACT_EFFECTS_ARMORPIERCING,
            self::DESTINY_TALENT_NODE_STEP_IMPACT_EFFECTS_RICOCHET,
            self::DESTINY_TALENT_NODE_STEP_IMPACT_EFFECTS_FLINCH,
            self::DESTINY_TALENT_NODE_STEP_IMPACT_EFFECTS_COLLATERALDAMAGE,
            self::DESTINY_TALENT_NODE_STEP_IMPACT_EFFECTS_DISORIENT,
            self::DESTINY_TALENT_NODE_STEP_IMPACT_EFFECTS_HIGHLIGHTTARGET,
            self::DESTINY_TALENT_NODE_STEP_IMPACT_EFFECTS_ALL,
        ];
    }
}


