<?php
/**
 * DestinyTalentNodeStepLightAbilities
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny\Definitions;
use \Bungie\D1\ObjectSerializer;

/**
 * DestinyTalentNodeStepLightAbilities Class Doc Comment
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DestinyTalentNodeStepLightAbilities
{
    /**
     * Possible values of this enum
     */
    const DESTINY_TALENT_NODE_STEP_LIGHT_ABILITIES_NONE = 0;
    const DESTINY_TALENT_NODE_STEP_LIGHT_ABILITIES_GRENADES = 1;
    const DESTINY_TALENT_NODE_STEP_LIGHT_ABILITIES_MELEE = 2;
    const DESTINY_TALENT_NODE_STEP_LIGHT_ABILITIES_MOVEMENTMODES = 4;
    const DESTINY_TALENT_NODE_STEP_LIGHT_ABILITIES_ORBS = 8;
    const DESTINY_TALENT_NODE_STEP_LIGHT_ABILITIES_SUPERENERGY = 16;
    const DESTINY_TALENT_NODE_STEP_LIGHT_ABILITIES_SUPERMODS = 32;
    const DESTINY_TALENT_NODE_STEP_LIGHT_ABILITIES_ALL = 63;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DESTINY_TALENT_NODE_STEP_LIGHT_ABILITIES_NONE,
            self::DESTINY_TALENT_NODE_STEP_LIGHT_ABILITIES_GRENADES,
            self::DESTINY_TALENT_NODE_STEP_LIGHT_ABILITIES_MELEE,
            self::DESTINY_TALENT_NODE_STEP_LIGHT_ABILITIES_MOVEMENTMODES,
            self::DESTINY_TALENT_NODE_STEP_LIGHT_ABILITIES_ORBS,
            self::DESTINY_TALENT_NODE_STEP_LIGHT_ABILITIES_SUPERENERGY,
            self::DESTINY_TALENT_NODE_STEP_LIGHT_ABILITIES_SUPERMODS,
            self::DESTINY_TALENT_NODE_STEP_LIGHT_ABILITIES_ALL,
        ];
    }
}


