<?php
/**
 * BungieMembershipType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model;
use \Bungie\D1\ObjectSerializer;

/**
 * BungieMembershipType Class Doc Comment
 *
 * @category Class
 * @description The types of membership the Accounts system supports. This is the external facing enum used in place of the internal-only Bungie.SharedDefinitions.MembershipType.
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BungieMembershipType
{
    /**
     * Possible values of this enum
     */
    const BUNGIE_MEMBERSHIP_TYPE_NONE = 0;
    const BUNGIE_MEMBERSHIP_TYPE_TIGERXBOX = 1;
    const BUNGIE_MEMBERSHIP_TYPE_TIGERPSN = 2;
    const BUNGIE_MEMBERSHIP_TYPE_TIGERBLIZZARD = 4;
    const BUNGIE_MEMBERSHIP_TYPE_TIGERDEMON = 10;
    const BUNGIE_MEMBERSHIP_TYPE_BUNGIENEXT = 254;
    const BUNGIE_MEMBERSHIP_TYPE_ALL = -1;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BUNGIE_MEMBERSHIP_TYPE_NONE,
            self::BUNGIE_MEMBERSHIP_TYPE_TIGERXBOX,
            self::BUNGIE_MEMBERSHIP_TYPE_TIGERPSN,
            self::BUNGIE_MEMBERSHIP_TYPE_TIGERBLIZZARD,
            self::BUNGIE_MEMBERSHIP_TYPE_TIGERDEMON,
            self::BUNGIE_MEMBERSHIP_TYPE_BUNGIENEXT,
            self::BUNGIE_MEMBERSHIP_TYPE_ALL,
        ];
    }
}


