<?php
/**
 * BucketCategory
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny;
use \Bungie\D1\ObjectSerializer;

/**
 * BucketCategory Class Doc Comment
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BucketCategory
{
    /**
     * Possible values of this enum
     */
    const BUCKET_CATEGORY_INVISIBLE = 0;
    const BUCKET_CATEGORY_ITEM = 1;
    const BUCKET_CATEGORY_CURRENCY = 2;
    const BUCKET_CATEGORY_EQUIPPABLE = 3;
    const BUCKET_CATEGORY_IGNORED = 4;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BUCKET_CATEGORY_INVISIBLE,
            self::BUCKET_CATEGORY_ITEM,
            self::BUCKET_CATEGORY_CURRENCY,
            self::BUCKET_CATEGORY_EQUIPPABLE,
            self::BUCKET_CATEGORY_IGNORED,
        ];
    }
}


