<?php
/**
 * DestinyRecordState
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny;
use \Bungie\D1\ObjectSerializer;

/**
 * DestinyRecordState Class Doc Comment
 *
 * @category Class
 * @description A Flags enumeration where each bit represents a possible state that a Record/Triumph can be in.
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DestinyRecordState
{
    /**
     * Possible values of this enum
     */
    const DESTINY_RECORD_STATE_NONE = 0;
    const DESTINY_RECORD_STATE_RECORDREDEEMED = 1;
    const DESTINY_RECORD_STATE_REWARDUNAVAILABLE = 2;
    const DESTINY_RECORD_STATE_OBJECTIVENOTCOMPLETED = 4;
    const DESTINY_RECORD_STATE_OBSCURED = 8;
    const DESTINY_RECORD_STATE_INVISIBLE = 16;
    const DESTINY_RECORD_STATE_ENTITLEMENTUNOWNED = 32;
    const DESTINY_RECORD_STATE_CANEQUIPTITLE = 64;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DESTINY_RECORD_STATE_NONE,
            self::DESTINY_RECORD_STATE_RECORDREDEEMED,
            self::DESTINY_RECORD_STATE_REWARDUNAVAILABLE,
            self::DESTINY_RECORD_STATE_OBJECTIVENOTCOMPLETED,
            self::DESTINY_RECORD_STATE_OBSCURED,
            self::DESTINY_RECORD_STATE_INVISIBLE,
            self::DESTINY_RECORD_STATE_ENTITLEMENTUNOWNED,
            self::DESTINY_RECORD_STATE_CANEQUIPTITLE,
        ];
    }
}


