<?php
/**
 * DestinyVendorInteractionRewardSelection
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny;
use \Bungie\D1\ObjectSerializer;

/**
 * DestinyVendorInteractionRewardSelection Class Doc Comment
 *
 * @category Class
 * @description When a Vendor Interaction provides rewards, they&#39;ll either let you choose one or let you have all of them. This determines which it will be.
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DestinyVendorInteractionRewardSelection
{
    /**
     * Possible values of this enum
     */
    const DESTINY_VENDOR_INTERACTION_REWARD_SELECTION_NONE = 0;
    const DESTINY_VENDOR_INTERACTION_REWARD_SELECTION_ONE = 1;
    const DESTINY_VENDOR_INTERACTION_REWARD_SELECTION_ALL = 2;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DESTINY_VENDOR_INTERACTION_REWARD_SELECTION_NONE,
            self::DESTINY_VENDOR_INTERACTION_REWARD_SELECTION_ONE,
            self::DESTINY_VENDOR_INTERACTION_REWARD_SELECTION_ALL,
        ];
    }
}


