<?php
/**
 * DestinyVendorReplyType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny;
use \Bungie\D1\ObjectSerializer;

/**
 * DestinyVendorReplyType Class Doc Comment
 *
 * @category Class
 * @description This determines the type of reply that a Vendor will have during an Interaction.
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DestinyVendorReplyType
{
    /**
     * Possible values of this enum
     */
    const DESTINY_VENDOR_REPLY_TYPE_ACCEPT = 0;
    const DESTINY_VENDOR_REPLY_TYPE_DECLINE = 1;
    const DESTINY_VENDOR_REPLY_TYPE_COMPLETE = 2;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DESTINY_VENDOR_REPLY_TYPE_ACCEPT,
            self::DESTINY_VENDOR_REPLY_TYPE_DECLINE,
            self::DESTINY_VENDOR_REPLY_TYPE_COMPLETE,
        ];
    }
}


