<?php
/**
 * DestinyGraphNodeState
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny;
use \Bungie\D1\ObjectSerializer;

/**
 * DestinyGraphNodeState Class Doc Comment
 *
 * @category Class
 * @description Represents a potential state of an Activity Graph node.
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DestinyGraphNodeState
{
    /**
     * Possible values of this enum
     */
    const DESTINY_GRAPH_NODE_STATE_HIDDEN = 0;
    const DESTINY_GRAPH_NODE_STATE_VISIBLE = 1;
    const DESTINY_GRAPH_NODE_STATE_TEASER = 2;
    const DESTINY_GRAPH_NODE_STATE_INCOMPLETE = 3;
    const DESTINY_GRAPH_NODE_STATE_COMPLETED = 4;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DESTINY_GRAPH_NODE_STATE_HIDDEN,
            self::DESTINY_GRAPH_NODE_STATE_VISIBLE,
            self::DESTINY_GRAPH_NODE_STATE_TEASER,
            self::DESTINY_GRAPH_NODE_STATE_INCOMPLETE,
            self::DESTINY_GRAPH_NODE_STATE_COMPLETED,
        ];
    }
}


