<?php
/**
 * DestinyProgressionScope
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny;
use \Bungie\D1\ObjectSerializer;

/**
 * DestinyProgressionScope Class Doc Comment
 *
 * @category Class
 * @description There are many Progressions in Destiny (think Character Level, or Reputation). These are the various \&quot;Scopes\&quot; of Progressions, which affect many things: * Where/if they are stored * How they are calculated * Where they can be used in other game logic
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DestinyProgressionScope
{
    /**
     * Possible values of this enum
     */
    const DESTINY_PROGRESSION_SCOPE_ACCOUNT = 0;
    const DESTINY_PROGRESSION_SCOPE_CHARACTER = 1;
    const DESTINY_PROGRESSION_SCOPE_CLAN = 2;
    const DESTINY_PROGRESSION_SCOPE_ITEM = 3;
    const DESTINY_PROGRESSION_SCOPE_IMPLICITFROMEQUIPMENT = 4;
    const DESTINY_PROGRESSION_SCOPE_MAPPED = 5;
    const DESTINY_PROGRESSION_SCOPE_MAPPEDAGGREGATE = 6;
    const DESTINY_PROGRESSION_SCOPE_MAPPEDSTAT = 7;
    const DESTINY_PROGRESSION_SCOPE_MAPPEDUNLOCKVALUE = 8;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DESTINY_PROGRESSION_SCOPE_ACCOUNT,
            self::DESTINY_PROGRESSION_SCOPE_CHARACTER,
            self::DESTINY_PROGRESSION_SCOPE_CLAN,
            self::DESTINY_PROGRESSION_SCOPE_ITEM,
            self::DESTINY_PROGRESSION_SCOPE_IMPLICITFROMEQUIPMENT,
            self::DESTINY_PROGRESSION_SCOPE_MAPPED,
            self::DESTINY_PROGRESSION_SCOPE_MAPPEDAGGREGATE,
            self::DESTINY_PROGRESSION_SCOPE_MAPPEDSTAT,
            self::DESTINY_PROGRESSION_SCOPE_MAPPEDUNLOCKVALUE,
        ];
    }
}


