<?php
/**
 * EquipFailureReason
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny;
use \Bungie\D1\ObjectSerializer;

/**
 * EquipFailureReason Class Doc Comment
 *
 * @category Class
 * @description The reasons why an item cannot be equipped, if any. Many flags can be set, or \&quot;None\&quot; if
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EquipFailureReason
{
    /**
     * Possible values of this enum
     */
    const EQUIP_FAILURE_REASON_NONE = 0;
    const EQUIP_FAILURE_REASON_ITEMUNEQUIPPABLE = 1;
    const EQUIP_FAILURE_REASON_ITEMUNIQUEEQUIPRESTRICTED = 2;
    const EQUIP_FAILURE_REASON_ITEMFAILEDUNLOCKCHECK = 4;
    const EQUIP_FAILURE_REASON_ITEMFAILEDLEVELCHECK = 8;
    const EQUIP_FAILURE_REASON_ITEMNOTONCHARACTER = 16;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EQUIP_FAILURE_REASON_NONE,
            self::EQUIP_FAILURE_REASON_ITEMUNEQUIPPABLE,
            self::EQUIP_FAILURE_REASON_ITEMUNIQUEEQUIPRESTRICTED,
            self::EQUIP_FAILURE_REASON_ITEMFAILEDUNLOCKCHECK,
            self::EQUIP_FAILURE_REASON_ITEMFAILEDLEVELCHECK,
            self::EQUIP_FAILURE_REASON_ITEMNOTONCHARACTER,
        ];
    }
}


