<?php
/**
 * ItemLocation
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny;
use \Bungie\D1\ObjectSerializer;

/**
 * ItemLocation Class Doc Comment
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ItemLocation
{
    /**
     * Possible values of this enum
     */
    const ITEM_LOCATION_UNKNOWN = 0;
    const ITEM_LOCATION_INVENTORY = 1;
    const ITEM_LOCATION_VAULT = 2;
    const ITEM_LOCATION_VENDOR = 3;
    const ITEM_LOCATION_POSTMASTER = 4;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ITEM_LOCATION_UNKNOWN,
            self::ITEM_LOCATION_INVENTORY,
            self::ITEM_LOCATION_VAULT,
            self::ITEM_LOCATION_VENDOR,
            self::ITEM_LOCATION_POSTMASTER,
        ];
    }
}


