<?php
/**
 * ItemState
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny;
use \Bungie\D1\ObjectSerializer;

/**
 * ItemState Class Doc Comment
 *
 * @category Class
 * @description A flags enumeration where each bit represents a different possible state that the item can be in that may effect how the item is displayed to the user and what actions can be performed against it.
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ItemState
{
    /**
     * Possible values of this enum
     */
    const ITEM_STATE_NONE = 0;
    const ITEM_STATE_LOCKED = 1;
    const ITEM_STATE_TRACKED = 2;
    const ITEM_STATE_MASTERWORK = 4;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ITEM_STATE_NONE,
            self::ITEM_STATE_LOCKED,
            self::ITEM_STATE_TRACKED,
            self::ITEM_STATE_MASTERWORK,
        ];
    }
}


