<?php
/**
 * ItemPerkVisibility
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny;
use \Bungie\D1\ObjectSerializer;

/**
 * ItemPerkVisibility Class Doc Comment
 *
 * @category Class
 * @description Indicates how a perk should be shown, or if it should be, in the game UI. Maybe useful for those of you trying to filter out internal-use-only perks (or for those of you trying to figure out what they do!)
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ItemPerkVisibility
{
    /**
     * Possible values of this enum
     */
    const ITEM_PERK_VISIBILITY_VISIBLE = 0;
    const ITEM_PERK_VISIBILITY_DISABLED = 1;
    const ITEM_PERK_VISIBILITY_HIDDEN = 2;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ITEM_PERK_VISIBILITY_VISIBLE,
            self::ITEM_PERK_VISIBILITY_DISABLED,
            self::ITEM_PERK_VISIBILITY_HIDDEN,
        ];
    }
}


