<?php
/**
 * PeriodType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny;
use \Bungie\D1\ObjectSerializer;

/**
 * PeriodType Class Doc Comment
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PeriodType
{
    /**
     * Possible values of this enum
     */
    const PERIOD_TYPE_NONE = 0;
    const PERIOD_TYPE_DAILY = 1;
    const PERIOD_TYPE_MONTHLY = 2;
    const PERIOD_TYPE_ALLTIME = 3;
    const PERIOD_TYPE_ACTIVITY = 4;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PERIOD_TYPE_NONE,
            self::PERIOD_TYPE_DAILY,
            self::PERIOD_TYPE_MONTHLY,
            self::PERIOD_TYPE_ALLTIME,
            self::PERIOD_TYPE_ACTIVITY,
        ];
    }
}


