<?php
/**
 * PlugUiStyles
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny;
use \Bungie\D1\ObjectSerializer;

/**
 * PlugUiStyles Class Doc Comment
 *
 * @category Class
 * @description If the plug has a specific custom style, this enumeration will represent that style/those styles.
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PlugUiStyles
{
    /**
     * Possible values of this enum
     */
    const PLUG_UI_STYLES_NONE = 0;
    const PLUG_UI_STYLES_MASTERWORK = 1;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PLUG_UI_STYLES_NONE,
            self::PLUG_UI_STYLES_MASTERWORK,
        ];
    }
}


