<?php
/**
 * PlugAvailabilityMode
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny;
use \Bungie\D1\ObjectSerializer;

/**
 * PlugAvailabilityMode Class Doc Comment
 *
 * @category Class
 * @description This enum determines whether the plug is available to be inserted.  - Normal means that all existing rules for plug insertion apply.  - UnavailableIfSocketContainsMatchingPlugCategory means that the plug is only available if the socket does NOT match the plug category.  - AvailableIfSocketContainsMatchingPlugCategory means that the plug is only available if the socket DOES match the plug category.  For category matching, use the plug&#39;s \&quot;plugCategoryIdentifier\&quot; property, comparing it to
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PlugAvailabilityMode
{
    /**
     * Possible values of this enum
     */
    const PLUG_AVAILABILITY_MODE_NORMAL = 0;
    const PLUG_AVAILABILITY_MODE_UNAVAILABLEIFSOCKETCONTAINSMATCHINGPLUGCATEGORY = 1;
    const PLUG_AVAILABILITY_MODE_AVAILABLEIFSOCKETCONTAINSMATCHINGPLUGCATEGORY = 2;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PLUG_AVAILABILITY_MODE_NORMAL,
            self::PLUG_AVAILABILITY_MODE_UNAVAILABLEIFSOCKETCONTAINSMATCHINGPLUGCATEGORY,
            self::PLUG_AVAILABILITY_MODE_AVAILABLEIFSOCKETCONTAINSMATCHINGPLUGCATEGORY,
        ];
    }
}


