<?php
/**
 * SocketPlugSources
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny;
use \Bungie\D1\ObjectSerializer;

/**
 * SocketPlugSources Class Doc Comment
 *
 * @category Class
 * @description Indicates how a socket is populated, and where you should look for valid plug data. This is a flags enumeration field, as you may have to look in multiple sources across multiple components for valid plugs.
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SocketPlugSources
{
    /**
     * Possible values of this enum
     */
    const SOCKET_PLUG_SOURCES_NONE = 0;
    const SOCKET_PLUG_SOURCES_INVENTORYSOURCED = 1;
    const SOCKET_PLUG_SOURCES_REUSABLEPLUGITEMS = 2;
    const SOCKET_PLUG_SOURCES_PROFILEPLUGSET = 4;
    const SOCKET_PLUG_SOURCES_CHARACTERPLUGSET = 8;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SOCKET_PLUG_SOURCES_NONE,
            self::SOCKET_PLUG_SOURCES_INVENTORYSOURCED,
            self::SOCKET_PLUG_SOURCES_REUSABLEPLUGITEMS,
            self::SOCKET_PLUG_SOURCES_PROFILEPLUGSET,
            self::SOCKET_PLUG_SOURCES_CHARACTERPLUGSET,
        ];
    }
}


