<?php
/**
 * SocketTypeActionType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny;
use \Bungie\D1\ObjectSerializer;

/**
 * SocketTypeActionType Class Doc Comment
 *
 * @category Class
 * @description Indicates the type of actions that can be performed
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SocketTypeActionType
{
    /**
     * Possible values of this enum
     */
    const SOCKET_TYPE_ACTION_TYPE_INSERTPLUG = 0;
    const SOCKET_TYPE_ACTION_TYPE_INFUSEITEM = 1;
    const SOCKET_TYPE_ACTION_TYPE_REINITIALIZESOCKET = 2;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SOCKET_TYPE_ACTION_TYPE_INSERTPLUG,
            self::SOCKET_TYPE_ACTION_TYPE_INFUSEITEM,
            self::SOCKET_TYPE_ACTION_TYPE_REINITIALIZESOCKET,
        ];
    }
}


