<?php
/**
 * TransferStatuses
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Unofficial Bungie.net API for Destiny 1
 *
 * These are legacy endpoints for Destiny 1 that are no longer supported officially by Bungie.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: lowlines89@gmail.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bungie\D1\Model\Destiny;
use \Bungie\D1\ObjectSerializer;

/**
 * TransferStatuses Class Doc Comment
 *
 * @category Class
 * @description Whether you can transfer an item, and why not if you can&#39;t.
 * @package  Bungie\D1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransferStatuses
{
    /**
     * Possible values of this enum
     */
    const TRANSFER_STATUSES_CANTRANSFER = 0;
    const TRANSFER_STATUSES_ITEMISEQUIPPED = 1;
    const TRANSFER_STATUSES_NOTTRANSFERRABLE = 2;
    const TRANSFER_STATUSES_NOROOMINDESTINATION = 4;
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TRANSFER_STATUSES_CANTRANSFER,
            self::TRANSFER_STATUSES_ITEMISEQUIPPED,
            self::TRANSFER_STATUSES_NOTTRANSFERRABLE,
            self::TRANSFER_STATUSES_NOROOMINDESTINATION,
        ];
    }
}


